### ISSUE TITLE
Multi-disk albums are grouped incorrectly

### ISSUE THREAD

**Issue by andreyorst** [Taiko2k/TauonMusicBox#1063]
I have a three-disk album that is stored like this:

```
Album Name
├── CD1
│   ├── cd_rip.flac
│   └── cd_rip.cue
├── CD2
│   ├── cd_rip.flac
│   └── cd_rip.cue
└── CD3
    ├── cd_rip.flac
    └── cd_rip.cue
```
File names inside the directories are identical, and all of the album metadata is also identical, except for the `disk` field, which is set correctly for each file.

After importing the release into the Tauon I get this kind of view:

```
________________________________________Album Name
track1 from cd1
________________________________________Album Name
track1 from cd2
________________________________________Album Name
track1 from cd3
________________________________________Album Name
track2 from cd1
________________________________________Album Name
track2 from cd2
________________________________________Album Name
track2 from cd3
________________________________________Album Name
track3 from cd1
________________________________________Album Name
track3 from cd2
________________________________________Album Name
track3 from cd3
________________________________________Album Name
track4 from cd1
________________________________________Album Name
track4 from cd2
________________________________________Album Name
track4 from cd3
...
```

Instead of the expected:

```
________________________________________Album Name
track1 from cd1
track2 from cd1
track3 from cd1
track4 from cd1
...
________________________________________Album Name
track1 from cd2
track2 from cd2
track3 from cd2
track4 from cd2
...
________________________________________Album Name
track1 from cd3
track2 from cd3
track3 from cd3
track4 from cd3
...
```

Other music players don't have issues with such releases in my library, so it shouldn't be a problem with the metadata. Perhaps Tauon doesn't use the Disk metadata for grouping.

<hr>

Tauon Music Box v7.7.0 from Flathub
OS: Fedora Silverblue 39

**Comment by Taiko2k** [comment]
This is supposed to work, but is an ongoing issue of fixing edge cases. Its difficult for me to work on this without a test case, so it would be helpful if you could zip up one of those albums and send it to me and I can see whats going on. (Keep the folder structure and .cue files, but you can omit the audio files themselves.)

**Comment by andreyorst** [comment]
sure. This is hand-constructed, but I've managed to reproduce the issue with it: [album.zip](https://github.com/Taiko2k/TauonMusicBox/files/13550024/album.zip)

![image](https://github.com/Taiko2k/TauonMusicBox/assets/19470159/9fc26933-7d47-447e-8ccf-1edca1472fcb)

Strawberry (Clementine fork) shows it like this:

![image](https://github.com/Taiko2k/TauonMusicBox/assets/19470159/2ec20a35-de4f-4b19-a023-4b063cb489b0)

but I know for sure that it relies on the metadata in the flac file itself, because if I change the CD there, the situation is the same as in Tauon

**Comment by Taiko2k** [comment]
Currently Tauon doesn't scan tags from the actual audio file at all when using a CUE sheet, so yes that help explain it. Ive now committed a change so that it will now inherit tags from the audio file. I assume this should fix the issue.

**Comment by andreyorst** [comment]
I have updated to the 7.7.1 release and unfortunately the problem persists.

**Comment by C0rn3j** [comment]
Could you drop the full repro case (including the music files) over here?

https://cloud.rys.rs/s/g82Yb52ifx53wHy

**Comment by andreyorst** [comment]
sorry, I changed my OS, and no longer have the files.

Are these from the https://github.com/Taiko2k/TauonMusicBox/files/13550024/album.zip not able to reproduce the problem?

**Comment by C0rn3j** [comment]
> Are these from the [Taiko2k/TauonMusicBox/files/13550024/album.zip](https://github.com/Taiko2k/TauonMusicBox/files/13550024/album.zip) not able to reproduce the problem?

Not on their own, they miss the audio files.

**Comment by andreyorst** [comment]
if I'm not mistaken, cue sheets are just text and can probably be pointed to any audio file. But I no longer have this release, so I can't upload it (and I probably would avoid uploading music on the internet entirely, as it could be considered piracy)

On a side note, I don't use Tauon anymore, so to me this issue has no priority - I'm ok if you just close it. This one is probably rare enough
