### ISSUE TITLE
GUI scale is reset when leaving mini-mode

### ISSUE THREAD

**Issue by toto789** [Taiko2k/TauonMusicBox#1145]
Tauon v7.7.2 on ubuntu 24.04
Steps to reproduce :
- Set GUI scale to 1.75x
- display Tauon in mini-mode
- quit mini-mode
Gui scale is reset to 1.00x.

**Comment by C0rn3j** [comment]
When you say mini-mode do you mean F8?

Do you still have the issue on the latest [development build](https://github.com/Taiko2k/Tauon/wiki/Development-builds)?

**Comment by toto789** [comment]
Yes, F8 or right-clic in the bottom panel > Mini.
How to test the development version? I didn't find an INSTALL file there.

**Comment by C0rn3j** [comment]
The download is an archive with an executable inside, just run the executable

**Comment by toto789** [comment]
Please explain to me step by step what I need to download (url etc.) and the name of the executable.
https://github-com.translate.goog/Taiko2k/Tauon?_x_tr_sl=auto&_x_tr_tl=fr&_x_tr_hl=fr and the run.sh file contained does not launch Tauon (typing ./run.sh
in a terminal I get:
```
1) Clean venv run
2) Dirty venv run
3) Windows build
4) Compile phazor
5) Compile phazor with PipeWire support
Select a script to run: 
```).

**Comment by C0rn3j** [comment]
It looks like you're following the building on Windows page instead of the development prebuilts page I linked.

Follow this - https://github.com/Taiko2k/Tauon/wiki/Development-builds

Not this - https://github.com/Taiko2k/Tauon/wiki/Building-for-Windows

I've edited the page a little to hopefully make things a bit more clear.


> the name of the executable

![image](https://github.com/user-attachments/assets/b2f52911-43d2-4259-ae0c-0aae29f4f121)

**Comment by toto789** [comment]
What is the url of the the Summary page, please?

**Comment by C0rn3j** [comment]
I've reworded it further, hopefully that makes it clearer, I plan to create proper pre-releases on the Releases page from it, but this will have to do for now.

**Comment by toto789** [comment]
It's much worse: any right-click choice on the menu icon at the bottom (Mini etc.) instantly closes Tauon almost every time, otherwise the resizing problem persists.

Here are the terminal messages on a crash:

```
$ ./Tauon
UserWarning: Using SDL2 binaries from pysdl2-dll 2.30.10
2024-12-30 20:22:53 [ INFO  ] [ __main__ ] Tauon v7.9.0
2024-12-30 20:22:53 [ INFO  ] [ __main__ ] Copyright 2015-2024 Taiko2k captain.gxj@gmail.com

2024-12-30 20:22:54 [ INFO  ] [  t_draw  ] Found jxlpy for JPEG XL support
2024-12-30 20:22:54 [ INFO  ] [  t_main  ] Window size: [1920, 1032]
Gtk-Message: 20:22:54.483: Failed to load module "canberra-gtk-module"
2024-12-30 20:22:54 [ INFO  ] [  t_main  ] Running in portable mode
2024-12-30 20:22:54 [ INFO  ] [  t_main  ] Found XDG-Downloads: /home/[XXX]/Téléchargements in /home/[XXX]/.config/user-dirs.dirs
2024-12-30 20:22:54 [ INFO  ] [  t_main  ] Found XDG-Music:     /home/[XXX]/Musique     in /home/[XXX]/.config/user-dirs.dirs
2024-12-30 20:22:54 [ INFO  ] [  t_main  ] Install directory:         /home/[XXX]/Bureau/TauonMusicBox/_internal
2024-12-30 20:22:54 [ INFO  ] [  t_main  ] Config directory:          /home/[XXX]/Bureau/TauonMusicBox/_internal/user-data
2024-12-30 20:22:54 [ INFO  ] [  t_main  ] Cache directory:           /home/[XXX]/Bureau/TauonMusicBox/_internal/cache
2024-12-30 20:22:54 [ INFO  ] [  t_main  ] Home directory:            /home/[XXX]
2024-12-30 20:22:54 [ INFO  ] [  t_main  ] Music directory:           /home/[XXX]/Musique
2024-12-30 20:22:54 [ INFO  ] [  t_main  ] Download directory:        /home/[XXX]/Téléchargements
2024-12-30 20:22:54 [ INFO  ] [  t_main  ] Asset directory:           /home/[XXX]/Bureau/TauonMusicBox/_internal/assets
2024-12-30 20:22:54 [ INFO  ] [  t_main  ] Locale directory:          /home/[XXX]/Bureau/TauonMusicBox/_internal/locale
2024-12-30 20:22:54 [WARNING] [  t_main  ] Star database file is missing, first run? Will create one anew! (t_main.py:3028)
2024-12-30 20:22:54 [WARNING] [  t_main  ] Album star database file is missing, first run? Will create one anew! (t_main.py:3045)
2024-12-30 20:22:54 [ INFO  ] [  t_main  ] Database loaded in 0.0 seconds.
2024-12-30 20:22:54 [ INFO  ] [  t_main  ] Translation file for 'None' loaded
2024-12-30 20:22:54 [ INFO  ] [ t_chrome ] Scanning for chromecasts...
2024-12-30 20:22:54 [ INFO  ] [discovery ] discover_chromecasts is deprecated and will be removed in June 2024, update to use CastBrowser instead.
2024-12-30 20:22:54 [ INFO  ] [t_webserve] Start controller server
2024-12-30 20:22:54 [ INFO  ] [  t_main  ] OPEN URI
2024-12-30 20:22:54 [ INFO  ] [  t_main  ] Using SDL version: 2.30.10
2024-12-30 20:22:54 [ INFO  ] [  t_main  ] Applying theme: Turbo
2024-12-30 20:22:54 [ INFO  ] [  t_main  ] Refill shuffle pool
2024-12-30 20:22:57 [ INFO  ] [  t_main  ] Writing database to disk... 
2024-12-30 20:22:57 [ INFO  ] [  t_main  ] Done writing database
Exit PHAzOR
2024-12-30 20:23:12 [ ERROR ] [  t_main  ] Window width is less than 500, grrr why does this happen, stupid bug (t_main.py:43687)
2024-12-30 20:23:12 [ ERROR ] [  t_main  ] Window width is less than 500, grrr why does this happen, stupid bug (t_main.py:43687)
Traceback (most recent call last):
  File "tauon/__main__.py", line 443, in <module>
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 384, in exec_module
  File "tauon/t_modules/t_main.py", line 47522, in <module>
  File "tauon/t_modules/t_main.py", line 33473, in render
UnboundLocalError: cannot access local variable 'seek_r' where it is not associated with a value
[PYI-10185:ERROR] Failed to execute script '__main__' due to unhandled exception!
2024-12-30 20:23:12 [WARNING] [ warnings ] asyncio/base_events.py:759: ResourceWarning: unclosed event loop <_UnixSelectorEventLoop running=False closed=False debug=False>
 (warnings.py:110)
```

**Comment by C0rn3j** [comment]
This is Ubuntu 24.04 and GNOME?

I am betting on the failed-to-load `canberra-gtk-module` breaking the image completely there, I tested on Plasma.

**Comment by toto789** [comment]
I am now under ubuntu 24.10, session "ubuntu on Xorg", GNOME-Shell.
I download, test the indicated package and come back...

**Comment by toto789** [comment]
There is still a small improvement: when we do not crash (the "Tab" layout seems less "fragile"), the resizing is preserved.

**Comment by C0rn3j** [comment]
So basically your initial problem is solved, but these prebuilts crash for you?

Can you test if you also get the same crash on a Wayland session, or if it's only limited to X?

**Comment by toto789** [comment]
On Wayland the terminal responds:
```
$./'Tauon Music Box'
UserWarning: Using SDL2 binaries from pysdl2-dll 2.30.10
2024-12-30 22:07:37 [ INFO ] [ __main__ ] Tauon v7.9.0
2024-12-30 22:07:37 [ INFO ] [ __main__ ] Copyright 2015-2025 Taiko2k captain.gxj@gmail.com

./Tauon Music Box: symbol lookup error: /lib/x86_64-linux-gnu/libEGL_mesa.so.0: undefined symbol: wl_display_create_queue_with_name
```

**Comment by toto789** [comment]
Alas! No, the problem is not solved: back on Xorg, I switch to Mini mode without crashing, and when returning to normal mode I lose the resizing again.

**Comment by C0rn3j** [comment]
I managed to reproduce the crash on my setup, seems exclusive to the prebuilt images, for some reason.

If you can run Tauon yourself from my branch you will probably no longer suffer the crashes, but I imagine your original issue (which I am having trouble reproducing) will still be there. I'll dig into that after figuring out what to do with the crashes, which are a bigger issue.

> ./Tauon Music Box: symbol lookup error: /lib/x86_64-linux-gnu/libEGL_mesa.so.0: undefined symbol: wl_display_create_queue_with_name

The question is if it's a failure of the pyinstaller packaging, or something wrong with your system. I imagine 24.04 dependencies/libraries may not like the 24.10 system.

Can you grab my fork with the `device` branch and run `./run.sh 1` off it (the first option to run in Clean venv) and see if you can reproduce the crashing issues there? Both the X one and the Wayland one.

Something like this:

```bash
sudo apt install -y libayatana-appindicator3-dev gir1.2-rsvg-2.0 libpipewire-0.3-dev libdbus-1-dev libsdl2-2.0-0 libsdl2-image-2.0-0 fonts-noto gir1.2-notify-0.7 libcairo2-dev python3-gi-cairo libwavpack-dev libsamplerate0-dev libopenmpt-dev libvorbis-dev libopusfile-dev libflac-dev libgme-dev libmpg123-dev

git clone git@github.com:C0rn3j/Tauon.git
cd Tauon
git checkout device
./run.sh 1
```

The dependency list is made on 24.04, but it will hopefully be the same for 24.10.

**Comment by toto789** [comment]
Your device branch with ./run.sh 1 (on Xorg):

```
[...]
src/phazor/phazor.c:25:17: note: ‘#pragma message: Note: C23 not supported! Current __STDC_VERSION__ value: 201710L’
   25 |         #pragma message("Note: C23 not supported! Current __STDC_VERSION__ value: " TOSTRING(__STDC_VERSION__))
      |                 ^~~~~~~
src/phazor/phazor.c:86:10: fatal error: samplerate.h: Aucun fichier ou dossier de ce nom
   86 | #include <samplerate.h>
      |          ^~~~~~~~~~~~~~
compilation terminated.
error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1

ERROR Backend subprocess exited when trying to invoke build_wheel
```

**Comment by C0rn3j** [comment]
That would suggest you did not run the first command and do not have `libsamplerate0-dev` installed, have you?

**Comment by toto789** [comment]
About X seek_r and Wayland mesa:
```
$ git clone git@github.com:C0rn3j/Tauon.git
Clonage dans 'Tauon'...
The authenticity of host 'github.com (140.82.121.4)' can't be established.
ED25519 key fingerprint is SHA256:+DiY3wvvV6TuJJhbpZisF/zLDA0zPMSvHdkr4UvCOqU.
This key is not known by any other names.
Are you sure you want to continue connecting (yes/no/[fingerprint])? y
Please type 'yes', 'no' or the fingerprint: yes
Warning: Permanently added 'github.com' (ED25519) to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Impossible de lire le dépôt distant.

Veuillez vérifier que vous avez les droits d'accès
et que le dépôt existe.
```
(means: Unable to read the remote repository. Please check that you have access rights and that the repository exists.)

**Comment by C0rn3j** [comment]
Whoops, gave you the git link instead of http, fixed the command (`git clone https://github.com/C0rn3j/Tauon.git`)

**Comment by toto789** [comment]
Same problems (still on Xorg): crashes and lost resizing.

**Comment by C0rn3j** [comment]
`seek_r` - Looking at the code - do you have no track playing when you do this, and does it work fine if you do have something playing?

**Comment by toto789** [comment]
Resize lost during playback.
It's 0:19 at my place. See you later!

**Comment by C0rn3j** [comment]
I meant if you are able to reproduce the crashing with seek_r during playback, since to me it seems like this is a bug that assumes that something will always play.

**Comment by toto789** [comment]
Indeed, with your version, the command ./run.sh 1 and on Xorg, if a song is playing, changes in display modes do not crash Tauon.
See you tomorrow for the rest, if you want!

**Comment by C0rn3j** [comment]
https://github.com/Taiko2k/Tauon/actions/runs/12557615679?pr=1361

This should fix the seek_r crash (minimode looks fairly blank when you run into this situation, but it beats a crash).

Can you check if ./run.sh 1 works on Wayland and if it has your scaling reset issue?

You probably want to do `git pull` in the cloned directory, to pull the seek_r crash there.

**Comment by toto789** [comment]
It crashes on Xorg before any song is played by switching, for example in "Mini" mode or "Large square", but not "Tab" (and with "Tab" the resizing is preserved).
Result of the test under Wayland in a few minutes...

**Comment by C0rn3j** [comment]
Post the crash log please

**Comment by toto789** [comment]
Crash log, after switching to "Mini" on Wayland, before any song playback:
```
[...]
2024-12-31 11:53:51 [WARNING] [ warnings ] /usr/lib/python3.12/asyncio/base_events.py:726: ResourceWarning: unclosed event loop <_UnixSelectorEventLoop running=False closed=False debug=False>
  _warn(f"unclosed event loop {self!r}", ResourceWarning, source=self)
 (warnings.py:112)
Traceback (most recent call last):
  File "/home/guegant/Bureau/Tauon-device/Tauon-device/Tauon/.venv/bin/tauonmb", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/guegant/Bureau/Tauon-device/Tauon-device/Tauon/.venv/lib/python3.12/site-packages/tauon/__main__.py", line 439, in main
    from tauon.t_modules import t_main
  File "/home/guegant/Bureau/Tauon-device/Tauon-device/Tauon/.venv/lib/python3.12/site-packages/tauon/t_modules/t_main.py", line 47131, in <module>
    mini_mode.render()
  File "/home/guegant/Bureau/Tauon-device/Tauon-device/Tauon/.venv/lib/python3.12/site-packages/tauon/t_modules/t_main.py", line 33085, in render
    left_area = (1, y1, seek_r[0] - 1, 45 * gui.scale)
                        ^^^^^^
UnboundLocalError: cannot access local variable 'seek_r' where it is not associated with a value
```

**Comment by C0rn3j** [comment]
> First, is this the right command (I'm not familiar with git)?

just `git pull` is enough, I was not aware you can supply it a URL...

That crash should not happen anymore on the image I posted and after `git pull && run.sh 1` from the device branch, I presume you ran it with 2 (dirty venv) which does not do a rebuild - try with a rebuild.

Do you have the scaling issue on Wayland?

**Comment by toto789** [comment]
I use the command:
`~/Desktop/Tauon-device/Tauon-device/Tauon$ ./run.sh 1`

On Xorg as on Wayland the scaling problem no longer appears... when Tauon does not crash, that is to say when using the "Tab" mode. So I can't know for the other modes.

**Comment by C0rn3j** [comment]
It shouldn't crash on `seek_r` anywhere anymore, can you check that [this commit](https://github.com/Taiko2k/Tauon/pull/1361/commits/28f471df80584977883df37c38f01029a45b8ebd) is present in this file:

`.venv/lib/python3.12/site-packages/tauon/t_modules/t_main.py`

and that it still truly gives you that crash there? Because it did fix it on my side.

**Comment by toto789** [comment]
Attention:
```
$ git pull && run.sh 1
Déjà à jour.
run.sh : commande introuvable
```
(commande introuvable = command not found). It works better with `git pull && ./run.sh 1` ;-)

Yes, my .venv/lib/python3.12/site-packages/tauon/t_modules/t_main.py file is compliant.

**Comment by C0rn3j** [comment]
Can you give the exact reproduction steps to get it to crash now?

Because if I launch Taoun here and mash F8 it no longer crashes.

[Screencast_20241231_122344.webm](https://github.com/user-attachments/assets/4c7af859-1c0b-4f4d-919e-3145a4d57091)

**Comment by C0rn3j** [comment]
Regarding you being unable to run the prebuilt images on Wayland, do they start working if you remove these four libwayland* files from the _internal directory?

![image](https://github.com/user-attachments/assets/e585355d-183d-43e8-8ae2-8f943fa5e146)

**Comment by toto789** [comment]
Steps to reproduce:
```
cd Bureau
cd Tauon
git pull && ./run.sh 1
```
-> Playlist empty
... Tauon no longer crashes!!! Olé! :-)

**Comment by toto789** [comment]
P.S. I agree to stay on Wayland... if you help me get Birdtray working properly there, which is the only reason I'm staying on Xorg. :-)

**Comment by toto789** [comment]
I note that I now have to double-click to change mode via the context menu in the bottom bar, as well as on the ˅ icon to exit a mode other than normal mode.

**Comment by C0rn3j** [comment]
> volume_r crash

If you redo those steps, it should be gone now, and hopefully not crash on a third thing.

> I agree to stay on Wayland... if you help me get Birdtray working properly there, which is the only reason I'm staying on Xorg

Me getting you to try Wayland was to nail the issue down, not to try to get you to switch, and now it's to diagnose the Wayland crashing issue, which is not reproducible on my HW+SW combo.

The latest prebuilt with the fixes included is here - https://github.com/Taiko2k/Tauon/actions/runs/12559236662 (still needs deleting the 4 _internal files and getting back as to if that helped)

That said, in the Wayland implementation thread on Birdtray's side, there are people suggesting alternative solutions that worked for them.

**Comment by toto789** [comment]
> Regarding you being unable to run the prebuilt images on Wayland, do they start working if you remove these four libwayland* files from the _internal directory?

I don't have any libwayland* files in my Tauon folder.

**Comment by C0rn3j** [comment]
They are exclusive to the prebuilt image, which is the thing that crashes on your system.

I.e. not the git cloned directory, but the zipped up download I linked to.

**Comment by toto789** [comment]
It doesn't seem to crash anymore, actually. I don't have to double-click the ˅ icon anymore, but still in the modes context menu.

**Comment by C0rn3j** [comment]
Can you clarify just to make sure we're talking about the same thing, since we're kinda sorting out three issues at the same time in this thread?

> It doesn't seem to crash anymore, actually.

A) The Wayland prebuilt on launching after deleting the 4 files in the prebuilt images
B) Prebuilt/direct launch when switching modes
C) Both crashes are now gone

**Comment by toto789** [comment]
I downloaded the archive at https://github.com/Taiko2k/Tauon/actions/runs/12559236662, deleted the 4 libwayland* files, then ran the "Tauon Music Box" file: no crashes when testing all modes. There remains the annoying obligation to click twice in the mode menu and, apparently only in Mini mode, twice on the ˅ icon to exit it.

I don't understand what difference you make between this:
> B) Prebuilt/direct launch when switching view modes
and A).
I don't understand:
> C) Both crashes are now gone
I only see one crash: when changing display mode.

It's time for me to go buy my New Year's Eve dinner, so don't expect me for about an hour. Think about that too, huh? :-)

P.S. 2: I haven't actually used Tauon for over three months, in favor of gmusicbrowser for which I just spent over two months giving it its very first graphic theme (https://www.pling.com/p/2230712/).

**Comment by C0rn3j** [comment]
> I don't understand what difference you make between this:

https://github.com/Taiko2k/Tauon/issues/1145#issuecomment-2565917155

The prebuilt image has this extra crash on launch at the moment, thanks for getting back, I'll yeet libwayland from the images then + made a report upstream as that seems like an odd default to me https://github.com/pyinstaller/pyinstaller/issues/8963

> There remains the annoying obligation to click twice in the mode menu and, apparently only in Mini mode, twice on the ˅ icon to exit it.

I've noticed that in the input forms in the Accounts menu too, presumably a Wayland exclusive issue then.

**Comment by toto789** [comment]
Back on Xorg, I confirm that the 2-clicks problem is not there. However, under the previous conditions (archive from https://github.com/Taiko2k/Tauon/actions/runs/12559236662, the 4 libwayland* files deleted and Tauon launched from the "Tauon Music Box" file), resizing crashes Tauon (as soon as the cursor is released). This bug is completely new! :-(

**Comment by C0rn3j** [comment]
Got the log?

**Comment by toto789** [comment]
```
[...]
2024-12-31 16:28:58 [ INFO  ] [  t_main  ] Window overscale!
2024-12-31 16:28:58 [ INFO  ] [  t_main  ] Message: Échelle d'IU anormale détectée.L'option a été réinitialisée à 1x
2024-12-31 16:28:58 [ INFO  ] [  t_main  ] Done rendering icons
Traceback (most recent call last):
  File "tauon/__main__.py", line 442, in <module>
  File "tauon/__main__.py", line 439, in main
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 384, in exec_module
  File "tauon/t_modules/t_main.py", line 44223, in <module>
  File "tauon/t_modules/t_main.py", line 41827, in update_layout_do
  File "tauon/t_modules/t_main.py", line 41813, in reload_scale
  File "tauon/t_modules/t_main.py", line 896, in reload
TypeError: WhiteModImageAsset.__init__() takes 1 positional argument but 2 positional arguments (and 2 keyword-only arguments) were given
[PYI-40982:ERROR] Failed to execute script '__main__' due to unhandled exception!
2024-12-31 16:28:58 [WARNING] [ warnings ] asyncio/base_events.py:759: ResourceWarning: unclosed event loop <_UnixSelectorEventLoop running=False closed=False debug=False>
 (warnings.py:110)
```

**Comment by C0rn3j** [comment]
That would be something I recently broke in that PR yeah, thanks for catching that.

https://github.com/Taiko2k/Tauon/actions/runs/12561355455?pr=1361

This build should work fine, not requiring any deletion, hopefully with zero crashes.

The X scaling bug this issue is originally about is still present, as I have no clue how to fix that one…

**Comment by toto789** [comment]
The "Copy title to clipboard" option at the bottom of the display modes menu (with an empty playlist) crashes Tauon with:
```
[...]
Traceback (most recent call last):
  File "tauon/__main__.py", line 442, in <module>
  File "tauon/__main__.py", line 439, in main
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 384, in exec_module
  File "tauon/t_modules/t_main.py", line 47252, in <module>
  File "tauon/t_modules/t_main.py", line 8343, in render
  File "tauon/t_modules/t_main.py", line 22964, in copy_bb_metadata
AttributeError: 'NoneType' object has no attribute 'title'
[PYI-44076:ERROR] Failed to execute script '__main__' due to unhandled exception!
2024-12-31 16:55:15 [WARNING] [ warnings ] asyncio/base_events.py:759: ResourceWarning: unclosed event loop <_UnixSelectorEventLoop running=False closed=False debug=False>
 (warnings.py:110)
```


One more effort, and you will have earned a good New Year's Eve! :-)

**Comment by toto789** [comment]
The great news is that, even if you don't know why, the resizing problem has disappeared! Chill the champagne!

**Comment by C0rn3j** [comment]
> The great news is that, even if you don't know why, the resizing problem has disappeared!

That'd be because I fixed the issue in the log you sent :)

> The "Copy title to clipboard" option at the bottom of the display modes menu (with an empty playlist)

I fixed it but I had no clue how you're summoning it until I realized it's another bug I am not dealing with right now :/ #1368

**Comment by toto789** [comment]
> I fixed it
Are you saying there is a new fixed version available for download somewhere, so I can test it?

**Comment by C0rn3j** [comment]
It's still the `device` branch in my fork, also viewable in this PR - https://github.com/Taiko2k/Tauon/pull/1361

Would be this build - https://github.com/Taiko2k/Tauon/actions/runs/12561839441

**Comment by toto789** [comment]
Sorry... but with the version downloaded just now at https://github.com/Taiko2k/Tauon/actions/runs/12561839441
the resizing is lost (but no problem with the "Copy title to clipboard" option).

**Comment by C0rn3j** [comment]
Ahh, I thought you mean crash during resizing, not the scaling setting persisting.

That's not fixed, but am glad that the crashing is at bay for now.

**Comment by toto789** [comment]
Sorry... but you still don't deserve a single aperitif!
As a reminder, the title of this report is:
"GUI scaling is reset when switching view modes". You haven't moved forward an inch!
What time is it where you are? Do you still have time to do it?
