### ISSUE TITLE
When importing xspf playlist...

### ISSUE THREAD

**Issue by StrangeSeasOfThought** [Taiko2k/TauonMusicBox#239]
...list the tracks that couldn't be imported, so I can find and add them manually.

Something weird happened today: All my settings were gone (besides the config file), as well as all playlists. I didn't do anything besides some light browsing. I didn't update Tauon and/or Manjaro. I listened to some music, some more browsing, opened Tauon again, and everything was gone. Not much of an issue, 30 seconds to change the settings to my liking, another 30 secs to fix the columns view, and importing the playlists again.
That's when Tauon notified me that 5 tracks couldn't be imported (most likely because of some naming/characters issue).

So, it'd be useful for Tauon to tell me exactly which tracks/files couldn't be imported. Maybe log file?

**Comment by Taiko2k** [comment]
> Something weird happened today: All my settings were gone (besides the config file), as well as all playlists. 

Hmm, sounds like it might have crashed while writing data to disk.

> So, it'd be useful for Tauon to tell me exactly which tracks/files couldn't be imported. Maybe log file?

Yes, sounds like an idea.

**Comment by Taiko2k** [comment]
Okay, I've pushed some changes now. Now the missing tracks will be listed in a file named `tauon.log` in the user data folder.

Ive also changed state saving/loading to create an automatic backup in case of corruption.

**Comment by StrangeSeasOfThought** [comment]
That's odd. When I import the same playlist now, there's no error message (5-10 tracks failed earlier). Nothing in the log file either.

Comparing stats:

1,365 tracks (playlist), after importing: 1,357 tracks (Tauon).

**Comment by StrangeSeasOfThought** [comment]
Okay, importing tracks fails when there's a # somewhere.

**Comment by Taiko2k** [comment]
OK I think I understand whats going on. When a track fails to be located, it still creates a placeholder entry for it in the track list (Just it will be greyed out since the file wasn't found). When you import the 2nd time, it uses those created track entries from last time and thus and no longer reporting that the track is missing.

**Comment by StrangeSeasOfThought** [comment]
Makes sense. Yes.

**Comment by Taiko2k** [comment]
> Okay, tracks that have # in their file or folder name fail to import.

Looks like I might have been using a wrong escaping function, I've fixed this now.

> longer reporting that the track is missing.

I've made a change. It now checks if the file actually exists and should report the error.

**Comment by StrangeSeasOfThought** [comment]
1) # still not importing
2) Error is being reported. 
3) Two playlists bug is fixed.

**Comment by Taiko2k** [comment]
Seems to be working fine with # for me.

**Comment by StrangeSeasOfThought** [comment]
Importing XSPF playlist: /home/david/Music/565.xspf
-- Failed to locate track
-- -- Expected path: /home/david/Music/CHEEZE/Plain/CHEEZE%20-%20Room%20
-- -- Title: CHEEZE/Plain/CHEEZE - Room #501.mp3
-- Failed to locate track
-- -- Expected path: /home/david/Music/Gill/R.O.A.D%20PROJECT%20
-- -- Title: Gill/R.O.A.D PROJECT #1/Gill - But (Feat. Baek Ji Young).mp3
-- Failed to locate track
-- -- Expected path: /home/david/Music/THE%20KOXX/RED/THE%20KOXX%20-%20
-- -- Title: THE KOXX/RED/THE KOXX - #lol.mp3
-- Failed to locate track
-- -- Expected path: /home/david/Music/WH3N/Find%20Them%20All%20
-- -- Title: WH3N/Find Them All #1-WH3N/WH3N - Something That You Left.mp3
-- Failed to locate track
-- -- Expected path: /home/david/Music/WH3N/Find%20Them%20All%20
-- -- Title: WH3N/Find Them All #1-WH3N/WH3N - 25.mp3
Finished importing XSPF

**Comment by Taiko2k** [comment]
Thats... weird, it looks like the filepath is split over the path and title fields. The title should just be the title tag there. Was this XSPF file made in Tauon or another app. Can you inspect your XSPF file and see if there's anything obvious wrong about the formatting of those entries? 

(Ive pushed a change so update to that, but its unrelated to this.)

**Comment by StrangeSeasOfThought** [comment]
I use Cantata's smart playlist feature to create a .m3u playlist, import the .m3u to VLC, save the playlist as .xspf and import it into Tauon. ^^

Investigating...

**Comment by StrangeSeasOfThought** [comment]
The .m3u file is fine. When saving it to .xspf, VLC puts the path into the title whenever there's a #. So it's a VLC issue.

**Comment by Taiko2k** [comment]
Phew, not my bug :relieved:
